AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
STRIPE_PUBLISHABLE_KEY: 
STRIPE_SECRET_KEY: 
SECRET_KEY_BASE: 
DEVISE_SECRET_KEY: 
GMAIL_USERNAME:
GMAIL_PASSWORD: 
ADMIN_NAME: 
ADMIN_EMAIL: 
ADMIN_PASSWORD: 
ROLES: 
development:
  SENDGRID_USERNAME: 
  SENDGRID_PASSWORD: 
  AWS_BUCKET: 
  FACEBOOK_ID: 
  FACEBOOK_SECRET: 
production:
  AWS_BUCKET: 
  FACEBOOK_ID: 
  FACEBOOK_SECRET: 